// flow-typed signature: 16cb72b5d1c47297936a11e36e42ff3d
// flow-typed version: <<STUB>>/np_v^5.0.3/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'np'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'np' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'np/source/cli' {
  declare module.exports: any;
}

declare module 'np/source/config' {
  declare module.exports: any;
}

declare module 'np/source/git-tasks' {
  declare module.exports: any;
}

declare module 'np/source/git-util' {
  declare module.exports: any;
}

declare module 'np/source/index' {
  declare module.exports: any;
}

declare module 'np/source/new-github-release-url' {
  declare module.exports: any;
}

declare module 'np/source/npm/enable-2fa' {
  declare module.exports: any;
}

declare module 'np/source/npm/handle-npm-error' {
  declare module.exports: any;
}

declare module 'np/source/npm/publish' {
  declare module.exports: any;
}

declare module 'np/source/npm/util' {
  declare module.exports: any;
}

declare module 'np/source/prerequisite-tasks' {
  declare module.exports: any;
}

declare module 'np/source/pretty-version-diff' {
  declare module.exports: any;
}

declare module 'np/source/release-task-helper' {
  declare module.exports: any;
}

declare module 'np/source/ui' {
  declare module.exports: any;
}

declare module 'np/source/util' {
  declare module.exports: any;
}

declare module 'np/source/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'np/source/cli.js' {
  declare module.exports: $Exports<'np/source/cli'>;
}
declare module 'np/source/config.js' {
  declare module.exports: $Exports<'np/source/config'>;
}
declare module 'np/source/git-tasks.js' {
  declare module.exports: $Exports<'np/source/git-tasks'>;
}
declare module 'np/source/git-util.js' {
  declare module.exports: $Exports<'np/source/git-util'>;
}
declare module 'np/source/index.js' {
  declare module.exports: $Exports<'np/source/index'>;
}
declare module 'np/source/new-github-release-url.js' {
  declare module.exports: $Exports<'np/source/new-github-release-url'>;
}
declare module 'np/source/npm/enable-2fa.js' {
  declare module.exports: $Exports<'np/source/npm/enable-2fa'>;
}
declare module 'np/source/npm/handle-npm-error.js' {
  declare module.exports: $Exports<'np/source/npm/handle-npm-error'>;
}
declare module 'np/source/npm/publish.js' {
  declare module.exports: $Exports<'np/source/npm/publish'>;
}
declare module 'np/source/npm/util.js' {
  declare module.exports: $Exports<'np/source/npm/util'>;
}
declare module 'np/source/prerequisite-tasks.js' {
  declare module.exports: $Exports<'np/source/prerequisite-tasks'>;
}
declare module 'np/source/pretty-version-diff.js' {
  declare module.exports: $Exports<'np/source/pretty-version-diff'>;
}
declare module 'np/source/release-task-helper.js' {
  declare module.exports: $Exports<'np/source/release-task-helper'>;
}
declare module 'np/source/ui.js' {
  declare module.exports: $Exports<'np/source/ui'>;
}
declare module 'np/source/util.js' {
  declare module.exports: $Exports<'np/source/util'>;
}
declare module 'np/source/version.js' {
  declare module.exports: $Exports<'np/source/version'>;
}
